<?php
/**
 * Error template
 *
 * This template can be overridden by copying it to yourtheme/chiptuningreseller/error.php.
 *
 * @package     ChiptuningReseller\Templates
 * @version     6.0.0
 *
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}
?>
<!-- START TEMPLATE -->
<div class="ctr-container ctr-mx-auto">
<?php ctr_get_template('partials/breadcrumbs.php', []); ?>
<div class="ctr-grid md:ctr-grid-cols-1 lg:ctr-grid-cols-2 ctr-gap-8">
        <div class="ctr-text-center">
        <img src="https://i.ibb.co/ck1SGFJ/Group.png" />
        </div>
        <div>
            <h3 class="ctr-text-xl ctr-m-5"><?php _e('Sorry, we can\'t find what you\'re looking for', 'ctr'); ?></h3>
            <p class="ctr-m-5">Looks like you are asking something we can't deliver. If you think this page should show something and it's not, then please contact the site admin</p>
            <a href="<?php ctr_print_full_start_url(); ?>" class="ctr-ml-5 sm:ctr-w-full lg:ctr-w-auto ctr-mt-8 ctr-border ctr-rounded ctr-md ctr-py-4 ctr-px-8 ctr-text-center ctr-bg-orange-600 ctr-text-white ctr-hover:ctr-bg-orange-700 focus:ctr-outline-none focus:ctr-ring-2 focus:ctr-ring-orange-700 focus:ctr-ring-opacity-50">
                <svg xmlns="http://www.w3.org/2000/svg" style="width:16px; height:16px;display:inline-block" class="ctr--mt-1 ctr-mr-5 ctr-fill-white" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg><?php _e('Take me to the chiptuning start page', 'ctr'); ?>
            </a>
            <p class="ctr-m-5 ctr-text-xs ctr-mt-7 ctr-mb-10">This page was generated by the <a href="https://chiptuningreseller.com" target="_blank">ChiptuningReseller</a> WP Plugin - Show vehicle data in your Wordpress Site</p>
        </div>
    </div>
</div>